//! List of commonly used strings in Javascript code.

use super::JsString;
use crate::{JsStr, StaticString};
use paste::paste;
use rustc_hash::FxHashMap;
use std::sync::LazyLock;

macro_rules! well_known_statics {
    ( $( $(#[$attr:meta])* ($name:ident, $string:literal) ),+$(,)? ) => {
        $(
            paste!{
                #[doc = "Gets the static `JsString` for `\"" $string "\"`."]
                pub const $name: JsString = const {
                    JsString::from_static(Self::find_static_js_string($string))
                };
            }
        )+
    };
}

/// List of commonly used strings in Javascript code.
///
/// Any strings defined here are used as a static [`JsString`] instead of allocating on the heap.
#[derive(Debug, Clone, Copy)]
pub struct StaticJsStrings;

impl StaticJsStrings {
    // useful to search at compile time a certain string in the array
    const fn find_static_js_string(candidate: &str) -> &'static StaticString {
        const fn const_eq(lhs: &[u8], rhs: &[u8]) -> bool {
            if lhs.len() != rhs.len() {
                return false;
            }

            let mut i = 0;
            while i < lhs.len() {
                if lhs[i] != rhs[i] {
                    return false;
                }
                i += 1;
            }
            true
        }

        let len = RAW_STATICS.len();
        let mut i = 0;
        while i < len {
            let Some(s) = RAW_STATICS[i].str.as_ascii() else {
                // All static strings are ascii encoded
                unreachable!()
            };
            if const_eq(s.as_bytes(), candidate.as_bytes()) {
                return &RAW_STATICS[i];
            }
            i += 1;
        }

        panic!("couldn't find the required string on the common string array");
    }

    /// Gets the `JsString` corresponding to `string`, or `None` if the string
    /// doesn't exist inside the static array.
    #[inline]
    #[must_use]
    pub fn get_string(string: &JsStr<'_>) -> Option<JsString> {
        if string.len() > MAX_STATIC_LENGTH {
            return None;
        }

        let static_str = *RAW_STATICS_CACHE.get(string)?;
        Some(JsString::from_static(static_str))
    }

    /// Gets the `JsStr` corresponding to `string`, or `None` if the string
    /// doesn't exist inside the static array.
    #[inline]
    #[must_use]
    pub fn get_js_str(string: &JsStr<'_>) -> Option<JsStr<'static>> {
        if string.len() > MAX_STATIC_LENGTH {
            return None;
        }

        Some(RAW_STATICS_CACHE.get(string)?.str)
    }

    // Some consts are only used on certain features, which triggers the unused lint.
    well_known_statics! {
        (EMPTY_STRING, ""),
        (LENGTH, "length"),
        // Symbols
        (SYMBOL_ASYNC_ITERATOR, "Symbol.asyncIterator"),
        (SYMBOL_HAS_INSTANCE, "Symbol.hasInstance"),
        (SYMBOL_IS_CONCAT_SPREADABLE, "Symbol.isConcatSpreadable"),
        (SYMBOL_ITERATOR, "Symbol.iterator"),
        (SYMBOL_MATCH, "Symbol.match"),
        (SYMBOL_MATCH_ALL, "Symbol.matchAll"),
        (SYMBOL_REPLACE, "Symbol.replace"),
        (SYMBOL_SEARCH, "Symbol.search"),
        (SYMBOL_SPECIES, "Symbol.species"),
        (SYMBOL_SPLIT, "Symbol.split"),
        (SYMBOL_TO_PRIMITIVE, "Symbol.toPrimitive"),
        (SYMBOL_TO_STRING_TAG, "Symbol.toStringTag"),
        (SYMBOL_UNSCOPABLES, "Symbol.unscopables"),
        (FN_SYMBOL_ASYNC_ITERATOR, "[Symbol.asyncIterator]"),
        (FN_SYMBOL_HAS_INSTANCE, "[Symbol.hasInstance]"),
        (FN_SYMBOL_IS_CONCAT_SPREADABLE, "[Symbol.isConcatSpreadable]"),
        (FN_SYMBOL_ITERATOR, "[Symbol.iterator]"),
        (FN_SYMBOL_MATCH, "[Symbol.match]"),
        (FN_SYMBOL_MATCH_ALL, "[Symbol.matchAll]"),
        (FN_SYMBOL_REPLACE, "[Symbol.replace]"),
        (FN_SYMBOL_SEARCH, "[Symbol.search]"),
        (FN_SYMBOL_SPECIES, "[Symbol.species]"),
        (FN_SYMBOL_SPLIT, "[Symbol.split]"),
        (FN_SYMBOL_TO_PRIMITIVE, "[Symbol.toPrimitive]"),
        (FN_SYMBOL_TO_STRING_TAG, "[Symbol.toStringTag]"),
        (FN_SYMBOL_UNSCOPABLES, "[Symbol.unscopables]"),
        // Builtins
        (ARRAY, "Array"),
        (ARRAY_BUFFER, "ArrayBuffer"),
        (SHARED_ARRAY_BUFFER, "SharedArrayBuffer"),
        (ASYNC_FUNCTION, "AsyncFunction"),
        (ASYNC_GENERATOR, "AsyncGenerator"),
        (ASYNC_GENERATOR_FUNCTION, "AsyncGeneratorFunction"),
        (ATOMICS, "Atomics"),
        (BIG_INT, "BigInt"),
        (BOOLEAN, "Boolean"),
        (DATA_VIEW, "DataView"),
        (DATE, "Date"),
        (ERROR, "Error"),
        (AGGREGATE_ERROR, "AggregateError"),
        (EVAL_ERROR, "EvalError"),
        (RANGE_ERROR, "RangeError"),
        (REFERENCE_ERROR, "ReferenceError"),
        (SYNTAX_ERROR, "SyntaxError"),
        (TYPE_ERROR, "TypeError"),
        (URI_ERROR, "URIError"),
        (ESCAPE, "escape"),
        (UNESCAPE, "unescape"),
        (EVAL, "eval"),
        (FUNCTION, "Function"),
        (GENERATOR, "Generator"),
        (GENERATOR_FUNCTION, "GeneratorFunction"),
        (INTL, "Intl"),
        (COLLATOR, "Collator"),
        (LIST_FORMAT, "ListFormat"),
        (LOCALE, "Locale"),
        (PLURAL_RULES, "PluralRules"),
        (SEGMENTER, "Segmenter"),
        (DATE_TIME_FORMAT, "DateTimeFormat"),
        (JSON, "JSON"),
        (MAP, "Map"),
        (MATH, "Math"),
        (NUMBER, "Number"),
        (NUMBER_FORMAT, "NumberFormat"),
        (IS_FINITE, "isFinite"),
        (IS_NAN, "isNaN"),
        (PARSE_INT, "parseInt"),
        (PARSE_FLOAT, "parseFloat"),
        (OBJECT, "Object"),
        (PROMISE, "Promise"),
        (PROXY, "Proxy"),
        (REFLECT, "Reflect"),
        (REG_EXP, "RegExp"),
        (SET, "Set"),
        (STRING, "String"),
        (SYMBOL, "Symbol"),
        (TYPED_ARRAY, "TypedArray"),
        (INT8_ARRAY, "Int8Array"),
        (UINT8_ARRAY, "Uint8Array"),
        (UINT8_CLAMPED_ARRAY, "Uint8ClampedArray"),
        (INT16_ARRAY, "Int16Array"),
        (UINT16_ARRAY, "Uint16Array"),
        (INT32_ARRAY, "Int32Array"),
        (UINT32_ARRAY, "Uint32Array"),
        (BIG_INT64_ARRAY, "BigInt64Array"),
        (BIG_UINT64_ARRAY, "BigUint64Array"),
        #[cfg(feature = "float16")]
        (FLOAT16_ARRAY, "Float16Array"),
        (FLOAT32_ARRAY, "Float32Array"),
        (FLOAT64_ARRAY, "Float64Array"),
        (ENCODE_URI, "encodeURI"),
        (ENCODE_URI_COMPONENT, "encodeURIComponent"),
        (DECODE_URI, "decodeURI"),
        (DECODE_URI_COMPONENT, "decodeURIComponent"),
        (WEAK_REF, "WeakRef"),
        (WEAK_MAP, "WeakMap"),
        (WEAK_SET, "WeakSet"),
        (TEMPORAL, "Temporal"),
        (NOW_TAG, "Temporal.Now"),
        (INSTANT_TAG, "Temporal.Instant"),
        (DURATION_TAG, "Temporal.Duration"),
        (PLAIN_DATE_TAG, "Temporal.PlainDate"),
        (PLAIN_DATETIME_TAG, "Temporal.PlainDateTime"),
        (PLAIN_TIME_TAG, "Temporal.PlainTime"),
        (PLAIN_YM_TAG, "Temporal.PlainYearMonth"),
        (PLAIN_MD_TAG, "Temporal.PlainMonthDay"),
        (ZONED_DT_TAG, "Temporal.ZonedDateTime"),
        (NOW_NAME, "Now"),
        (INSTANT_NAME, "Instant"),
        (DURATION_NAME, "Duration"),
        (PLAIN_DATE_NAME, "PlainDate"),
        (PLAIN_DATETIME_NAME, "PlainDateTime"),
        (PLAIN_TIME_NAME, "PlainTime"),
        (PLAIN_YM_NAME, "PlainYearMonth"),
        (PLAIN_MD_NAME, "PlainMonthDay"),
        (ZONED_DT_NAME, "ZonedDateTime"),
    }
}

const MAX_STATIC_LENGTH: usize = {
    let mut max = 0;
    let mut i = 0;
    while i < RAW_STATICS.len() {
        let len = RAW_STATICS[i].str.len();
        if len > max {
            max = len;
        }
        i += 1;
    }
    max
};

/// Map from a `JsStr` to its corresponding `StaticJsString`.
static RAW_STATICS_CACHE: LazyLock<FxHashMap<JsStr<'static>, &'static StaticString>> =
    LazyLock::new(|| RAW_STATICS.iter().map(|s| (s.str, s)).collect());

/// Array of raw static strings that aren't reference counted.
const RAW_STATICS: &[StaticString] = &[
    StaticString::new(JsStr::ascii("")),
    // Well known symbols
    StaticString::new(JsStr::ascii("Symbol.asyncIterator")),
    StaticString::new(JsStr::ascii("[Symbol.asyncIterator]")),
    StaticString::new(JsStr::ascii("Symbol.hasInstance")),
    StaticString::new(JsStr::ascii("[Symbol.hasInstance]")),
    StaticString::new(JsStr::ascii("Symbol.isConcatSpreadable")),
    StaticString::new(JsStr::ascii("[Symbol.isConcatSpreadable]")),
    StaticString::new(JsStr::ascii("Symbol.iterator")),
    StaticString::new(JsStr::ascii("[Symbol.iterator]")),
    StaticString::new(JsStr::ascii("Symbol.match")),
    StaticString::new(JsStr::ascii("[Symbol.match]")),
    StaticString::new(JsStr::ascii("Symbol.matchAll")),
    StaticString::new(JsStr::ascii("[Symbol.matchAll]")),
    StaticString::new(JsStr::ascii("Symbol.replace")),
    StaticString::new(JsStr::ascii("[Symbol.replace]")),
    StaticString::new(JsStr::ascii("Symbol.search")),
    StaticString::new(JsStr::ascii("[Symbol.search]")),
    StaticString::new(JsStr::ascii("Symbol.species")),
    StaticString::new(JsStr::ascii("[Symbol.species]")),
    StaticString::new(JsStr::ascii("Symbol.split")),
    StaticString::new(JsStr::ascii("[Symbol.split]")),
    StaticString::new(JsStr::ascii("Symbol.toPrimitive")),
    StaticString::new(JsStr::ascii("[Symbol.toPrimitive]")),
    StaticString::new(JsStr::ascii("Symbol.toStringTag")),
    StaticString::new(JsStr::ascii("[Symbol.toStringTag]")),
    StaticString::new(JsStr::ascii("Symbol.unscopables")),
    StaticString::new(JsStr::ascii("[Symbol.unscopables]")),
    StaticString::new(JsStr::ascii("get [Symbol.species]")),
    StaticString::new(JsStr::ascii("get [Symbol.toStringTag]")),
    // Well known builtins
    StaticString::new(JsStr::ascii("Array")),
    StaticString::new(JsStr::ascii("ArrayBuffer")),
    StaticString::new(JsStr::ascii("SharedArrayBuffer")),
    StaticString::new(JsStr::ascii("AsyncFunction")),
    StaticString::new(JsStr::ascii("AsyncGenerator")),
    StaticString::new(JsStr::ascii("AsyncGeneratorFunction")),
    StaticString::new(JsStr::ascii("Atomics")),
    StaticString::new(JsStr::ascii("BigInt")),
    StaticString::new(JsStr::ascii("Boolean")),
    StaticString::new(JsStr::ascii("DataView")),
    StaticString::new(JsStr::ascii("Date")),
    StaticString::new(JsStr::ascii("Error")),
    StaticString::new(JsStr::ascii("AggregateError")),
    StaticString::new(JsStr::ascii("EvalError")),
    StaticString::new(JsStr::ascii("RangeError")),
    StaticString::new(JsStr::ascii("ReferenceError")),
    StaticString::new(JsStr::ascii("SyntaxError")),
    StaticString::new(JsStr::ascii("TypeError")),
    StaticString::new(JsStr::ascii("URIError")),
    StaticString::new(JsStr::ascii("escape")),
    StaticString::new(JsStr::ascii("unescape")),
    StaticString::new(JsStr::ascii("eval")),
    StaticString::new(JsStr::ascii("Function")),
    StaticString::new(JsStr::ascii("Generator")),
    StaticString::new(JsStr::ascii("GeneratorFunction")),
    StaticString::new(JsStr::ascii("Intl")),
    StaticString::new(JsStr::ascii("Collator")),
    StaticString::new(JsStr::ascii("ListFormat")),
    StaticString::new(JsStr::ascii("Locale")),
    StaticString::new(JsStr::ascii("PluralRules")),
    StaticString::new(JsStr::ascii("Segmenter")),
    StaticString::new(JsStr::ascii("DateTimeFormat")),
    StaticString::new(JsStr::ascii("JSON")),
    StaticString::new(JsStr::ascii("Map")),
    StaticString::new(JsStr::ascii("Math")),
    StaticString::new(JsStr::ascii("Number")),
    StaticString::new(JsStr::ascii("NumberFormat")),
    StaticString::new(JsStr::ascii("isFinite")),
    StaticString::new(JsStr::ascii("isNaN")),
    StaticString::new(JsStr::ascii("parseInt")),
    StaticString::new(JsStr::ascii("parseFloat")),
    StaticString::new(JsStr::ascii("Object")),
    StaticString::new(JsStr::ascii("Promise")),
    StaticString::new(JsStr::ascii("Proxy")),
    StaticString::new(JsStr::ascii("Reflect")),
    StaticString::new(JsStr::ascii("RegExp")),
    StaticString::new(JsStr::ascii("Set")),
    StaticString::new(JsStr::ascii("String")),
    StaticString::new(JsStr::ascii("Symbol")),
    StaticString::new(JsStr::ascii("TypedArray")),
    StaticString::new(JsStr::ascii("Int8Array")),
    StaticString::new(JsStr::ascii("Uint8Array")),
    StaticString::new(JsStr::ascii("Uint8ClampedArray")),
    StaticString::new(JsStr::ascii("Int16Array")),
    StaticString::new(JsStr::ascii("Uint16Array")),
    StaticString::new(JsStr::ascii("Int32Array")),
    StaticString::new(JsStr::ascii("Uint32Array")),
    StaticString::new(JsStr::ascii("BigInt64Array")),
    StaticString::new(JsStr::ascii("BigUint64Array")),
    StaticString::new(JsStr::ascii("Float16Array")),
    StaticString::new(JsStr::ascii("Float32Array")),
    StaticString::new(JsStr::ascii("Float64Array")),
    StaticString::new(JsStr::ascii("encodeURI")),
    StaticString::new(JsStr::ascii("encodeURIComponent")),
    StaticString::new(JsStr::ascii("decodeURI")),
    StaticString::new(JsStr::ascii("decodeURIComponent")),
    StaticString::new(JsStr::ascii("WeakRef")),
    StaticString::new(JsStr::ascii("WeakMap")),
    StaticString::new(JsStr::ascii("WeakSet")),
    StaticString::new(JsStr::ascii("Temporal")),
    StaticString::new(JsStr::ascii("Temporal.Now")),
    StaticString::new(JsStr::ascii("Temporal.Instant")),
    StaticString::new(JsStr::ascii("Temporal.Duration")),
    StaticString::new(JsStr::ascii("Temporal.Calendar")),
    StaticString::new(JsStr::ascii("Temporal.PlainDate")),
    StaticString::new(JsStr::ascii("Temporal.PlainDateTime")),
    StaticString::new(JsStr::ascii("Temporal.PlainMonthDay")),
    StaticString::new(JsStr::ascii("Temporal.PlainYearMonth")),
    StaticString::new(JsStr::ascii("Temporal.PlainTime")),
    StaticString::new(JsStr::ascii("Temporal.TimeZone")),
    StaticString::new(JsStr::ascii("Temporal.ZonedDateTime")),
    // Misc
    StaticString::new(JsStr::ascii(",")),
    StaticString::new(JsStr::ascii(":")),
    // Generic use
    StaticString::new(JsStr::ascii("name")),
    StaticString::new(JsStr::ascii("length")),
    StaticString::new(JsStr::ascii("arguments")),
    StaticString::new(JsStr::ascii("prototype")),
    StaticString::new(JsStr::ascii("constructor")),
    StaticString::new(JsStr::ascii("return")),
    StaticString::new(JsStr::ascii("throw")),
    StaticString::new(JsStr::ascii("global")),
    StaticString::new(JsStr::ascii("globalThis")),
    // typeof
    StaticString::new(JsStr::ascii("null")),
    StaticString::new(JsStr::ascii("undefined")),
    StaticString::new(JsStr::ascii("number")),
    StaticString::new(JsStr::ascii("string")),
    StaticString::new(JsStr::ascii("symbol")),
    StaticString::new(JsStr::ascii("bigint")),
    StaticString::new(JsStr::ascii("object")),
    StaticString::new(JsStr::ascii("function")),
    // Property descriptor
    StaticString::new(JsStr::ascii("value")),
    StaticString::new(JsStr::ascii("get")),
    StaticString::new(JsStr::ascii("set")),
    StaticString::new(JsStr::ascii("writable")),
    StaticString::new(JsStr::ascii("enumerable")),
    StaticString::new(JsStr::ascii("configurable")),
    // Object object
    StaticString::new(JsStr::ascii("assign")),
    StaticString::new(JsStr::ascii("create")),
    StaticString::new(JsStr::ascii("toString")),
    StaticString::new(JsStr::ascii("valueOf")),
    StaticString::new(JsStr::ascii("is")),
    StaticString::new(JsStr::ascii("seal")),
    StaticString::new(JsStr::ascii("isSealed")),
    StaticString::new(JsStr::ascii("freeze")),
    StaticString::new(JsStr::ascii("isFrozen")),
    StaticString::new(JsStr::ascii("isExtensible")),
    StaticString::new(JsStr::ascii("hasOwnProperty")),
    StaticString::new(JsStr::ascii("isPrototypeOf")),
    StaticString::new(JsStr::ascii("setPrototypeOf")),
    StaticString::new(JsStr::ascii("getPrototypeOf")),
    StaticString::new(JsStr::ascii("defineProperty")),
    StaticString::new(JsStr::ascii("defineProperties")),
    StaticString::new(JsStr::ascii("deleteProperty")),
    StaticString::new(JsStr::ascii("construct")),
    StaticString::new(JsStr::ascii("hasOwn")),
    StaticString::new(JsStr::ascii("ownKeys")),
    StaticString::new(JsStr::ascii("keys")),
    StaticString::new(JsStr::ascii("values")),
    StaticString::new(JsStr::ascii("entries")),
    StaticString::new(JsStr::ascii("fromEntries")),
    StaticString::new(JsStr::ascii("propertyIsEnumerable")),
    StaticString::new(JsStr::ascii("preventExtensions")),
    StaticString::new(JsStr::ascii("getOwnPropertyDescriptor")),
    StaticString::new(JsStr::ascii("getOwnPropertyDescriptors")),
    StaticString::new(JsStr::ascii("getOwnPropertyNames")),
    StaticString::new(JsStr::ascii("getOwnPropertySymbols")),
    StaticString::new(JsStr::ascii("__defineGetter__")),
    StaticString::new(JsStr::ascii("__defineSetter__")),
    StaticString::new(JsStr::ascii("__lookupGetter__")),
    StaticString::new(JsStr::ascii("__lookupSetter__")),
    StaticString::new(JsStr::ascii("__proto__")),
    StaticString::new(JsStr::ascii("get __proto__")),
    StaticString::new(JsStr::ascii("set __proto__")),
    // Function object
    StaticString::new(JsStr::ascii("apply")),
    StaticString::new(JsStr::ascii("bind")),
    StaticString::new(JsStr::ascii("call")),
    StaticString::new(JsStr::ascii("caller")),
    // Arguments object
    StaticString::new(JsStr::ascii("callee")),
    // Array object
    StaticString::new(JsStr::ascii("at")),
    StaticString::new(JsStr::ascii("from")),
    StaticString::new(JsStr::ascii("isArray")),
    StaticString::new(JsStr::ascii("of")),
    StaticString::new(JsStr::ascii("copyWithin")),
    StaticString::new(JsStr::ascii("every")),
    StaticString::new(JsStr::ascii("fill")),
    StaticString::new(JsStr::ascii("filter")),
    StaticString::new(JsStr::ascii("find")),
    StaticString::new(JsStr::ascii("findIndex")),
    StaticString::new(JsStr::ascii("findLast")),
    StaticString::new(JsStr::ascii("findLastIndex")),
    StaticString::new(JsStr::ascii("flat")),
    StaticString::new(JsStr::ascii("flatMap")),
    StaticString::new(JsStr::ascii("forEach")),
    StaticString::new(JsStr::ascii("includes")),
    StaticString::new(JsStr::ascii("indexOf")),
    StaticString::new(JsStr::ascii("join")),
    StaticString::new(JsStr::ascii("map")),
    StaticString::new(JsStr::ascii("next")),
    StaticString::new(JsStr::ascii("reduce")),
    StaticString::new(JsStr::ascii("reduceRight")),
    StaticString::new(JsStr::ascii("reverse")),
    StaticString::new(JsStr::ascii("shift")),
    StaticString::new(JsStr::ascii("slice")),
    StaticString::new(JsStr::ascii("splice")),
    StaticString::new(JsStr::ascii("some")),
    StaticString::new(JsStr::ascii("sort")),
    StaticString::new(JsStr::ascii("unshift")),
    StaticString::new(JsStr::ascii("push")),
    StaticString::new(JsStr::ascii("pop")),
    StaticString::new(JsStr::ascii("groupBy")),
    StaticString::new(JsStr::ascii("toReversed")),
    StaticString::new(JsStr::ascii("toSorted")),
    StaticString::new(JsStr::ascii("toSpliced")),
    StaticString::new(JsStr::ascii("with")),
    // String object
    StaticString::new(JsStr::ascii("charAt")),
    StaticString::new(JsStr::ascii("charCodeAt")),
    StaticString::new(JsStr::ascii("codePointAt")),
    StaticString::new(JsStr::ascii("concat")),
    StaticString::new(JsStr::ascii("endsWith")),
    StaticString::new(JsStr::ascii("fromCharCode")),
    StaticString::new(JsStr::ascii("fromCodePoint")),
    StaticString::new(JsStr::ascii("lastIndexOf")),
    StaticString::new(JsStr::ascii("match")),
    StaticString::new(JsStr::ascii("matchAll")),
    StaticString::new(JsStr::ascii("normalize")),
    StaticString::new(JsStr::ascii("padEnd")),
    StaticString::new(JsStr::ascii("padStart")),
    StaticString::new(JsStr::ascii("raw")),
    StaticString::new(JsStr::ascii("repeat")),
    StaticString::new(JsStr::ascii("replace")),
    StaticString::new(JsStr::ascii("replaceAll")),
    StaticString::new(JsStr::ascii("search")),
    StaticString::new(JsStr::ascii("split")),
    StaticString::new(JsStr::ascii("startsWith")),
    StaticString::new(JsStr::ascii("substr")),
    StaticString::new(JsStr::ascii("substring")),
    StaticString::new(JsStr::ascii("toLocaleString")),
    StaticString::new(JsStr::ascii("toLowerCase")),
    StaticString::new(JsStr::ascii("toUpperCase")),
    StaticString::new(JsStr::ascii("trim")),
    StaticString::new(JsStr::ascii("trimEnd")),
    StaticString::new(JsStr::ascii("trimStart")),
    StaticString::new(JsStr::ascii("isWellFormed")),
    StaticString::new(JsStr::ascii("localeCompare")),
    StaticString::new(JsStr::ascii("toWellFormed")),
    StaticString::new(JsStr::ascii("toLocaleLowerCase")),
    StaticString::new(JsStr::ascii("toLocaleUpperCase")),
    StaticString::new(JsStr::ascii("trimLeft")),
    StaticString::new(JsStr::ascii("trimRight")),
    StaticString::new(JsStr::ascii("anchor")),
    StaticString::new(JsStr::ascii("big")),
    StaticString::new(JsStr::ascii("blink")),
    StaticString::new(JsStr::ascii("bold")),
    StaticString::new(JsStr::ascii("fixed")),
    StaticString::new(JsStr::ascii("fontcolor")),
    StaticString::new(JsStr::ascii("fontsize")),
    StaticString::new(JsStr::ascii("italics")),
    StaticString::new(JsStr::ascii("link")),
    StaticString::new(JsStr::ascii("small")),
    StaticString::new(JsStr::ascii("strike")),
    StaticString::new(JsStr::ascii("sub")),
    StaticString::new(JsStr::ascii("sup")),
    // Number object
    StaticString::new(JsStr::ascii("Infinity")),
    StaticString::new(JsStr::ascii("NaN")),
    StaticString::new(JsStr::ascii("EPSILON")),
    StaticString::new(JsStr::ascii("MAX_SAFE_INTEGER")),
    StaticString::new(JsStr::ascii("MIN_SAFE_INTEGER")),
    StaticString::new(JsStr::ascii("MAX_VALUE")),
    StaticString::new(JsStr::ascii("MIN_VALUE")),
    StaticString::new(JsStr::ascii("NEGATIVE_INFINITY")),
    StaticString::new(JsStr::ascii("POSITIVE_INFINITY")),
    StaticString::new(JsStr::ascii("isSafeInteger")),
    StaticString::new(JsStr::ascii("isInteger")),
    StaticString::new(JsStr::ascii("toExponential")),
    StaticString::new(JsStr::ascii("toFixed")),
    StaticString::new(JsStr::ascii("toPrecision")),
    // BigInt object
    StaticString::new(JsStr::ascii("asIntN")),
    StaticString::new(JsStr::ascii("asUintN")),
    // RegExp object
    StaticString::new(JsStr::ascii("exec")),
    StaticString::new(JsStr::ascii("test")),
    StaticString::new(JsStr::ascii("compile")),
    StaticString::new(JsStr::ascii("flags")),
    StaticString::new(JsStr::ascii("index")),
    StaticString::new(JsStr::ascii("lastIndex")),
    StaticString::new(JsStr::ascii("hasIndices")),
    StaticString::new(JsStr::ascii("ignoreCase")),
    StaticString::new(JsStr::ascii("multiline")),
    StaticString::new(JsStr::ascii("dotAll")),
    StaticString::new(JsStr::ascii("unicode")),
    StaticString::new(JsStr::ascii("sticky")),
    StaticString::new(JsStr::ascii("source")),
    StaticString::new(JsStr::ascii("get hasIndices")),
    StaticString::new(JsStr::ascii("get global")),
    StaticString::new(JsStr::ascii("get ignoreCase")),
    StaticString::new(JsStr::ascii("get multiline")),
    StaticString::new(JsStr::ascii("get dotAll")),
    StaticString::new(JsStr::ascii("get unicode")),
    StaticString::new(JsStr::ascii("get sticky")),
    StaticString::new(JsStr::ascii("get flags")),
    StaticString::new(JsStr::ascii("get source")),
    // Symbol object
    StaticString::new(JsStr::ascii("for")),
    StaticString::new(JsStr::ascii("keyFor")),
    StaticString::new(JsStr::ascii("description")),
    StaticString::new(JsStr::ascii("asyncIterator")),
    StaticString::new(JsStr::ascii("hasInstance")),
    StaticString::new(JsStr::ascii("species")),
    StaticString::new(JsStr::ascii("unscopables")),
    StaticString::new(JsStr::ascii("iterator")),
    StaticString::new(JsStr::ascii("toStringTag")),
    StaticString::new(JsStr::ascii("toPrimitive")),
    StaticString::new(JsStr::ascii("isConcatSpreadable")),
    StaticString::new(JsStr::ascii("get description")),
    // Map object
    StaticString::new(JsStr::ascii("clear")),
    StaticString::new(JsStr::ascii("delete")),
    StaticString::new(JsStr::ascii("has")),
    StaticString::new(JsStr::ascii("size")),
    // Set object
    StaticString::new(JsStr::ascii("add")),
    // Reflect object
    // Proxy object
    StaticString::new(JsStr::ascii("revocable")),
    // Error objects
    StaticString::new(JsStr::ascii("message")),
    // Date object
    StaticString::new(JsStr::ascii("toJSON")),
    StaticString::new(JsStr::ascii("getDate")),
    StaticString::new(JsStr::ascii("getDay")),
    StaticString::new(JsStr::ascii("getFullYear")),
    StaticString::new(JsStr::ascii("getHours")),
    StaticString::new(JsStr::ascii("getMilliseconds")),
    StaticString::new(JsStr::ascii("getMinutes")),
    StaticString::new(JsStr::ascii("getMonth")),
    StaticString::new(JsStr::ascii("getSeconds")),
    StaticString::new(JsStr::ascii("getTime")),
    StaticString::new(JsStr::ascii("getYear")),
    StaticString::new(JsStr::ascii("getUTCDate")),
    StaticString::new(JsStr::ascii("getUTCDay")),
    StaticString::new(JsStr::ascii("getUTCFullYear")),
    StaticString::new(JsStr::ascii("getUTCHours")),
    StaticString::new(JsStr::ascii("getUTCMinutes")),
    StaticString::new(JsStr::ascii("getUTCMonth")),
    StaticString::new(JsStr::ascii("getUTCSeconds")),
    StaticString::new(JsStr::ascii("setDate")),
    StaticString::new(JsStr::ascii("setFullYear")),
    StaticString::new(JsStr::ascii("setHours")),
    StaticString::new(JsStr::ascii("setMilliseconds")),
    StaticString::new(JsStr::ascii("setMinutes")),
    StaticString::new(JsStr::ascii("setMonth")),
    StaticString::new(JsStr::ascii("setSeconds")),
    StaticString::new(JsStr::ascii("setYear")),
    StaticString::new(JsStr::ascii("setTime")),
    StaticString::new(JsStr::ascii("setUTCDate")),
    StaticString::new(JsStr::ascii("setUTCFullYear")),
    StaticString::new(JsStr::ascii("setUTCHours")),
    StaticString::new(JsStr::ascii("setUTCMinutes")),
    StaticString::new(JsStr::ascii("setUTCMonth")),
    StaticString::new(JsStr::ascii("setUTCSeconds")),
    StaticString::new(JsStr::ascii("toDateString")),
    StaticString::new(JsStr::ascii("toGMTString")),
    StaticString::new(JsStr::ascii("toISOString")),
    StaticString::new(JsStr::ascii("toTimeString")),
    StaticString::new(JsStr::ascii("toUTCString")),
    StaticString::new(JsStr::ascii("now")),
    StaticString::new(JsStr::ascii("UTC")),
    StaticString::new(JsStr::ascii("getTimezoneOffset")),
    StaticString::new(JsStr::ascii("getUTCMilliseconds")),
    StaticString::new(JsStr::ascii("setUTCMilliseconds")),
    StaticString::new(JsStr::ascii("toLocaleDateString")),
    StaticString::new(JsStr::ascii("toLocaleTimeString")),
    // JSON object
    StaticString::new(JsStr::ascii("parse")),
    StaticString::new(JsStr::ascii("stringify")),
    // Promise object
    StaticString::new(JsStr::ascii("promise")),
    StaticString::new(JsStr::ascii("resolve")),
    StaticString::new(JsStr::ascii("reject")),
    StaticString::new(JsStr::ascii("all")),
    StaticString::new(JsStr::ascii("allSettled")),
    StaticString::new(JsStr::ascii("any")),
    StaticString::new(JsStr::ascii("race")),
    StaticString::new(JsStr::ascii("then")),
    StaticString::new(JsStr::ascii("catch")),
    StaticString::new(JsStr::ascii("finally")),
    StaticString::new(JsStr::ascii("withResolvers")),
    // Iterator object
    StaticString::new(JsStr::ascii("Array Iterator")),
    StaticString::new(JsStr::ascii("Set Iterator")),
    StaticString::new(JsStr::ascii("String Iterator")),
    StaticString::new(JsStr::ascii("Map Iterator")),
    StaticString::new(JsStr::ascii("For In Iterator")),
    StaticString::new(JsStr::ascii("RegExp String Iterator")),
    // Iterator result object
    StaticString::new(JsStr::ascii("done")),
    // Math object
    StaticString::new(JsStr::ascii("LN10")),
    StaticString::new(JsStr::ascii("LN2")),
    StaticString::new(JsStr::ascii("LOG10E")),
    StaticString::new(JsStr::ascii("LOG2E")),
    StaticString::new(JsStr::ascii("PI")),
    StaticString::new(JsStr::ascii("SQRT1_2")),
    StaticString::new(JsStr::ascii("SQRT2")),
    StaticString::new(JsStr::ascii("abs")),
    StaticString::new(JsStr::ascii("acos")),
    StaticString::new(JsStr::ascii("acosh")),
    StaticString::new(JsStr::ascii("asin")),
    StaticString::new(JsStr::ascii("asinh")),
    StaticString::new(JsStr::ascii("atan")),
    StaticString::new(JsStr::ascii("atanh")),
    StaticString::new(JsStr::ascii("atan2")),
    StaticString::new(JsStr::ascii("cbrt")),
    StaticString::new(JsStr::ascii("ceil")),
    StaticString::new(JsStr::ascii("clz32")),
    StaticString::new(JsStr::ascii("cos")),
    StaticString::new(JsStr::ascii("cosh")),
    StaticString::new(JsStr::ascii("exp")),
    StaticString::new(JsStr::ascii("expm1")),
    StaticString::new(JsStr::ascii("floor")),
    StaticString::new(JsStr::ascii("fround")),
    StaticString::new(JsStr::ascii("hypot")),
    StaticString::new(JsStr::ascii("imul")),
    StaticString::new(JsStr::ascii("log")),
    StaticString::new(JsStr::ascii("log1p")),
    StaticString::new(JsStr::ascii("log10")),
    StaticString::new(JsStr::ascii("log2")),
    StaticString::new(JsStr::ascii("max")),
    StaticString::new(JsStr::ascii("min")),
    StaticString::new(JsStr::ascii("pow")),
    StaticString::new(JsStr::ascii("random")),
    StaticString::new(JsStr::ascii("round")),
    StaticString::new(JsStr::ascii("sign")),
    StaticString::new(JsStr::ascii("sin")),
    StaticString::new(JsStr::ascii("sinh")),
    StaticString::new(JsStr::ascii("sqrt")),
    StaticString::new(JsStr::ascii("tan")),
    StaticString::new(JsStr::ascii("tanh")),
    StaticString::new(JsStr::ascii("trunc")),
    // TypedArray object
    StaticString::new(JsStr::ascii("BYTES_PER_ELEMENT")),
    StaticString::new(JsStr::ascii("buffer")),
    StaticString::new(JsStr::ascii("byteLength")),
    StaticString::new(JsStr::ascii("byteOffset")),
    StaticString::new(JsStr::ascii("isView")),
    StaticString::new(JsStr::ascii("subarray")),
    StaticString::new(JsStr::ascii("get byteLength")),
    StaticString::new(JsStr::ascii("get buffer")),
    StaticString::new(JsStr::ascii("get byteOffset")),
    StaticString::new(JsStr::ascii("get size")),
    StaticString::new(JsStr::ascii("get length")),
    // DataView object
    StaticString::new(JsStr::ascii("getBigInt64")),
    StaticString::new(JsStr::ascii("getBigUint64")),
    StaticString::new(JsStr::ascii("getFloat16")),
    StaticString::new(JsStr::ascii("getFloat32")),
    StaticString::new(JsStr::ascii("getFloat64")),
    StaticString::new(JsStr::ascii("getInt8")),
    StaticString::new(JsStr::ascii("getInt16")),
    StaticString::new(JsStr::ascii("getInt32")),
    StaticString::new(JsStr::ascii("getUint8")),
    StaticString::new(JsStr::ascii("getUint16")),
    StaticString::new(JsStr::ascii("getUint32")),
    StaticString::new(JsStr::ascii("setBigInt64")),
    StaticString::new(JsStr::ascii("setBigUint64")),
    StaticString::new(JsStr::ascii("setFloat16")),
    StaticString::new(JsStr::ascii("setFloat32")),
    StaticString::new(JsStr::ascii("setFloat64")),
    StaticString::new(JsStr::ascii("setInt8")),
    StaticString::new(JsStr::ascii("setInt16")),
    StaticString::new(JsStr::ascii("setInt32")),
    StaticString::new(JsStr::ascii("setUint8")),
    StaticString::new(JsStr::ascii("setUint16")),
    StaticString::new(JsStr::ascii("setUint32")),
    // WeakRef object
    StaticString::new(JsStr::ascii("deref")),
    // Atomic object
    StaticString::new(JsStr::ascii("and")),
    StaticString::new(JsStr::ascii("compareExchange")),
    StaticString::new(JsStr::ascii("exchange")),
    StaticString::new(JsStr::ascii("isLockFree")),
    StaticString::new(JsStr::ascii("load")),
    StaticString::new(JsStr::ascii("or")),
    StaticString::new(JsStr::ascii("store")),
    StaticString::new(JsStr::ascii("wait")),
    StaticString::new(JsStr::ascii("notify")),
    StaticString::new(JsStr::ascii("xor")),
    // Intl object
    StaticString::new(JsStr::ascii("getCanonicalLocales")),
    StaticString::new(JsStr::ascii("get compare")),
    StaticString::new(JsStr::ascii("supportedLocalesOf")),
    StaticString::new(JsStr::ascii("Intl.Collator")),
    StaticString::new(JsStr::ascii("compare")),
    StaticString::new(JsStr::ascii("resolvedOptions")),
    StaticString::new(JsStr::ascii("Intl.ListFormat")),
    StaticString::new(JsStr::ascii("format")),
    StaticString::new(JsStr::ascii("formatToParts")),
    StaticString::new(JsStr::ascii("get baseName")),
    StaticString::new(JsStr::ascii("get calendar")),
    StaticString::new(JsStr::ascii("get caseFirst")),
    StaticString::new(JsStr::ascii("get collation")),
    StaticString::new(JsStr::ascii("get hourCycle")),
    StaticString::new(JsStr::ascii("get numeric")),
    StaticString::new(JsStr::ascii("get numberingSystem")),
    StaticString::new(JsStr::ascii("get language")),
    StaticString::new(JsStr::ascii("get script")),
    StaticString::new(JsStr::ascii("get region")),
    StaticString::new(JsStr::ascii("Intl.Locale")),
    StaticString::new(JsStr::ascii("maximize")),
    StaticString::new(JsStr::ascii("minimize")),
    StaticString::new(JsStr::ascii("baseName")),
    StaticString::new(JsStr::ascii("calendar")),
    StaticString::new(JsStr::ascii("caseFirst")),
    StaticString::new(JsStr::ascii("collation")),
    StaticString::new(JsStr::ascii("hourCycle")),
    StaticString::new(JsStr::ascii("numeric")),
    StaticString::new(JsStr::ascii("numberingSystem")),
    StaticString::new(JsStr::ascii("language")),
    StaticString::new(JsStr::ascii("script")),
    StaticString::new(JsStr::ascii("region")),
    StaticString::new(JsStr::ascii("Intl.Segmenter")),
    StaticString::new(JsStr::ascii("segment")),
    StaticString::new(JsStr::ascii("containing")),
    StaticString::new(JsStr::ascii("Segmenter String Iterator")),
    StaticString::new(JsStr::ascii("Intl.PluralRules")),
    StaticString::new(JsStr::ascii("select")),
    // Temporal object
    StaticString::new(JsStr::ascii("get Id")),
    StaticString::new(JsStr::ascii("getOffsetNanosecondsFor")),
    StaticString::new(JsStr::ascii("getOffsetStringFor")),
    StaticString::new(JsStr::ascii("getPlainDateTimeFor")),
    StaticString::new(JsStr::ascii("getInstantFor")),
    StaticString::new(JsStr::ascii("getPossibleInstantFor")),
    StaticString::new(JsStr::ascii("getNextTransition")),
    StaticString::new(JsStr::ascii("getPreviousTransition")),
    StaticString::new(JsStr::ascii("id")),
    StaticString::new(JsStr::ascii("Now")),
    StaticString::new(JsStr::ascii("Calendar")),
    StaticString::new(JsStr::ascii("Duration")),
    StaticString::new(JsStr::ascii("Instant")),
    StaticString::new(JsStr::ascii("PlainDate")),
    StaticString::new(JsStr::ascii("PlainDateTime")),
    StaticString::new(JsStr::ascii("PlainMonthDay")),
    StaticString::new(JsStr::ascii("PlainTime")),
    StaticString::new(JsStr::ascii("PlainYearMonth")),
    StaticString::new(JsStr::ascii("TimeZone")),
    StaticString::new(JsStr::ascii("ZonedDateTime")),
    StaticString::new(JsStr::ascii("timeZoneId")),
    StaticString::new(JsStr::ascii("instant")),
    StaticString::new(JsStr::ascii("plainDateTime")),
    StaticString::new(JsStr::ascii("plainDateTimeISO")),
    StaticString::new(JsStr::ascii("zonedDateTime")),
    StaticString::new(JsStr::ascii("zonedDateTimeISO")),
    StaticString::new(JsStr::ascii("plainDate")),
    StaticString::new(JsStr::ascii("plainDateISO")),
    StaticString::new(JsStr::ascii("get epochSeconds")),
    StaticString::new(JsStr::ascii("get epochMilliseconds")),
    StaticString::new(JsStr::ascii("get epochMicroseconds")),
    StaticString::new(JsStr::ascii("get epochNanoseconds")),
    StaticString::new(JsStr::ascii("epochSeconds")),
    StaticString::new(JsStr::ascii("epochMilliseconds")),
    StaticString::new(JsStr::ascii("epochMicroseconds")),
    StaticString::new(JsStr::ascii("epochNanoseconds")),
    StaticString::new(JsStr::ascii("subtract")),
    StaticString::new(JsStr::ascii("until")),
    StaticString::new(JsStr::ascii("since")),
    StaticString::new(JsStr::ascii("equals")),
    StaticString::new(JsStr::ascii("toZonedDateTime")),
    StaticString::new(JsStr::ascii("toZonedDateTimeISO")),
    StaticString::new(JsStr::ascii("get Years")),
    StaticString::new(JsStr::ascii("get Months")),
    StaticString::new(JsStr::ascii("get Weeks")),
    StaticString::new(JsStr::ascii("get Days")),
    StaticString::new(JsStr::ascii("get Hours")),
    StaticString::new(JsStr::ascii("get Minutes")),
    StaticString::new(JsStr::ascii("get Seconds")),
    StaticString::new(JsStr::ascii("get Milliseconds")),
    StaticString::new(JsStr::ascii("get Microseconds")),
    StaticString::new(JsStr::ascii("get Nanoseconds")),
    StaticString::new(JsStr::ascii("get Sign")),
    StaticString::new(JsStr::ascii("get blank")),
    StaticString::new(JsStr::ascii("years")),
    StaticString::new(JsStr::ascii("months")),
    StaticString::new(JsStr::ascii("weeks")),
    StaticString::new(JsStr::ascii("days")),
    StaticString::new(JsStr::ascii("hours")),
    StaticString::new(JsStr::ascii("minutes")),
    StaticString::new(JsStr::ascii("seconds")),
    StaticString::new(JsStr::ascii("milliseconds")),
    StaticString::new(JsStr::ascii("microseconds")),
    StaticString::new(JsStr::ascii("nanoseconds")),
    StaticString::new(JsStr::ascii("blank")),
    StaticString::new(JsStr::ascii("negated")),
    StaticString::new(JsStr::ascii("total")),
    StaticString::new(JsStr::ascii("get calendarId")),
    StaticString::new(JsStr::ascii("get year")),
    StaticString::new(JsStr::ascii("get month")),
    StaticString::new(JsStr::ascii("get monthCode")),
    StaticString::new(JsStr::ascii("get day")),
    StaticString::new(JsStr::ascii("get dayOfWeek")),
    StaticString::new(JsStr::ascii("get dayOfYear")),
    StaticString::new(JsStr::ascii("get weekOfYear")),
    StaticString::new(JsStr::ascii("get yearOfWeek")),
    StaticString::new(JsStr::ascii("get daysInWeek")),
    StaticString::new(JsStr::ascii("get daysInMonth")),
    StaticString::new(JsStr::ascii("get daysInYear")),
    StaticString::new(JsStr::ascii("get monthsInYear")),
    StaticString::new(JsStr::ascii("get inLeapYear")),
    StaticString::new(JsStr::ascii("calendarId")),
    StaticString::new(JsStr::ascii("year")),
    StaticString::new(JsStr::ascii("month")),
    StaticString::new(JsStr::ascii("monthCode")),
    StaticString::new(JsStr::ascii("day")),
    StaticString::new(JsStr::ascii("dayOfWeek")),
    StaticString::new(JsStr::ascii("dayOfYear")),
    StaticString::new(JsStr::ascii("weekOfYear")),
    StaticString::new(JsStr::ascii("yearOfWeek")),
    StaticString::new(JsStr::ascii("daysInWeek")),
    StaticString::new(JsStr::ascii("daysInMonth")),
    StaticString::new(JsStr::ascii("daysInYear")),
    StaticString::new(JsStr::ascii("monthsInYear")),
    StaticString::new(JsStr::ascii("inLeapYear")),
    StaticString::new(JsStr::ascii("toPlainYearMonth")),
    StaticString::new(JsStr::ascii("toPlainMonthDay")),
    StaticString::new(JsStr::ascii("getISOFields")),
    StaticString::new(JsStr::ascii("getCalendar")),
    StaticString::new(JsStr::ascii("withCalendar")),
    StaticString::new(JsStr::ascii("dateFromFields")),
    StaticString::new(JsStr::ascii("yearMonthFromFields")),
    StaticString::new(JsStr::ascii("monthDayFromFields")),
    StaticString::new(JsStr::ascii("dateAdd")),
    StaticString::new(JsStr::ascii("dateUntil")),
    StaticString::new(JsStr::ascii("era")),
    StaticString::new(JsStr::ascii("eraYear")),
    StaticString::new(JsStr::ascii("fields")),
    StaticString::new(JsStr::ascii("mergeFields")),
    // Console object
    StaticString::new(JsStr::ascii("console")),
    StaticString::new(JsStr::ascii("assert")),
    StaticString::new(JsStr::ascii("debug")),
    StaticString::new(JsStr::ascii("error")),
    StaticString::new(JsStr::ascii("info")),
    StaticString::new(JsStr::ascii("trace")),
    StaticString::new(JsStr::ascii("warn")),
    StaticString::new(JsStr::ascii("exception")),
    StaticString::new(JsStr::ascii("count")),
    StaticString::new(JsStr::ascii("countReset")),
    StaticString::new(JsStr::ascii("group")),
    StaticString::new(JsStr::ascii("groupCollapsed")),
    StaticString::new(JsStr::ascii("groupEnd")),
    StaticString::new(JsStr::ascii("time")),
    StaticString::new(JsStr::ascii("timeLog")),
    StaticString::new(JsStr::ascii("timeEnd")),
    StaticString::new(JsStr::ascii("dir")),
    StaticString::new(JsStr::ascii("dirxml")),
    // Minified name
    StaticString::new(JsStr::ascii("a")),
    StaticString::new(JsStr::ascii("c")),
    StaticString::new(JsStr::ascii("d")),
    StaticString::new(JsStr::ascii("e")),
    StaticString::new(JsStr::ascii("f")),
    StaticString::new(JsStr::ascii("g")),
    StaticString::new(JsStr::ascii("h")),
    StaticString::new(JsStr::ascii("i")),
    StaticString::new(JsStr::ascii("j")),
    StaticString::new(JsStr::ascii("k")),
    StaticString::new(JsStr::ascii("l")),
    StaticString::new(JsStr::ascii("m")),
    StaticString::new(JsStr::ascii("n")),
    StaticString::new(JsStr::ascii("o")),
    StaticString::new(JsStr::ascii("p")),
    StaticString::new(JsStr::ascii("q")),
    StaticString::new(JsStr::ascii("r")),
    StaticString::new(JsStr::ascii("s")),
    StaticString::new(JsStr::ascii("t")),
    StaticString::new(JsStr::ascii("u")),
    StaticString::new(JsStr::ascii("v")),
    StaticString::new(JsStr::ascii("w")),
    StaticString::new(JsStr::ascii("x")),
    StaticString::new(JsStr::ascii("y")),
    StaticString::new(JsStr::ascii("z")),
    StaticString::new(JsStr::ascii("A")),
    StaticString::new(JsStr::ascii("C")),
    StaticString::new(JsStr::ascii("D")),
    StaticString::new(JsStr::ascii("E")),
    StaticString::new(JsStr::ascii("F")),
    StaticString::new(JsStr::ascii("G")),
    StaticString::new(JsStr::ascii("H")),
    StaticString::new(JsStr::ascii("I")),
    StaticString::new(JsStr::ascii("J")),
    StaticString::new(JsStr::ascii("K")),
    StaticString::new(JsStr::ascii("L")),
    StaticString::new(JsStr::ascii("M")),
    StaticString::new(JsStr::ascii("N")),
    StaticString::new(JsStr::ascii("O")),
    StaticString::new(JsStr::ascii("P")),
    StaticString::new(JsStr::ascii("Q")),
    StaticString::new(JsStr::ascii("R")),
    StaticString::new(JsStr::ascii("S")),
    StaticString::new(JsStr::ascii("T")),
    StaticString::new(JsStr::ascii("U")),
    StaticString::new(JsStr::ascii("V")),
    StaticString::new(JsStr::ascii("W")),
    StaticString::new(JsStr::ascii("X")),
    StaticString::new(JsStr::ascii("Y")),
    StaticString::new(JsStr::ascii("Z")),
    StaticString::new(JsStr::ascii("_")),
    StaticString::new(JsStr::ascii("$")),
];
